import { Amplifier } from "../type/amplifier";
import { Attribute, AttributeName } from "../type/attribute";
import { WDTYPE_NAMES } from "./weapon";

export const ATTRIBUTE_TYPES = [
  "Attribute",
  "Mod",
  "Talent",
  "Brandset",
  "Gearset",
] as const;

export const ATTRIBUTE_NAMES = [
  "Weapon Damage",
  ...WDTYPE_NAMES,
  "Critical Hit Chance",
  "Critical Hit Damage",
  "Headshot Damage",
  "Damage to Armor",
  "Damage to Health",
  "DMG to Target out of Cover",
  "Rate of Fire",
  "Magazine size",
  "Reload Speed",
  "Stability",
  "Accuracy",
  "Weapon Handling",
  "Optimal Range",
  "Ammo Capacity",
  "Swap Speed",
  "Armor",
  "Health",
  "Armor Regeneration",
  "Hazard Protection",
  "Explosive Resistance",
  "Skill Tier",
  "Status Effects",
  "Skill Efficiency",
  "Skill Repair",
  "Skill Damage",
  "Skill Haste",
  "Skill Duration",
  "< WDTalent >",
  "< TWD >",
  "< AMP1 >",
  "< AMP2 >",
  "< AMP3 >",
] as const;

export const ATTRIBUTES: Record<Amplifier, AttributeName[]> = {
  WDCore: ["Weapon Damage"],
  WDType: WDTYPE_NAMES,
  WDTalent: ["< WDTalent >"],
  TWD: ["< TWD >"],
  CHC: ["Critical Hit Chance"],
  CHD: ["Critical Hit Damage"],
  HS: ["Headshot Damage"],
  DTA: ["Damage to Armor"],
  DTH: ["Damage to Health"],
  DTTOOC: ["DMG to Target out of Cover"],
  AMP1: ["< AMP1 >"],
  AMP2: ["< AMP2 >"],
  AMP3: ["< AMP3 >"],
  ROF: ["Rate of Fire"],
  None: [
    "Magazine size",
    "Reload Speed",
    "Stability",
    "Accuracy",
    "Weapon Handling",
    "Optimal Range",
    "Ammo Capacity",
    "Swap Speed",
    "Armor",
    "Health",
    "Armor Regeneration",
    "Hazard Protection",
    "Explosive Resistance",
    "Skill Tier",
    "Status Effects",
    "Skill Efficiency",
    "Skill Repair",
    "Skill Damage",
    "Skill Haste",
    "Skill Duration",
  ],
};

export const DEFAULT_ATTRIBUTE: Attribute = {
  type: "Attribute",
  name: "Weapon Damage",
  value: 0.15,
  uptime: 1.0,
  note: "",
  amplifier: "WDCore",
};
