export const ATTRIBUTES = [
  "Weapon Damage",
  "Critical Hit Chance",
  "Critical Hit Damage",
  "Headshot Damage",
  "Damage to Armor",
  "Damage to Health",
  "DMG to Target out of Cover",
  "Rate of Fire",
  "Marksman Rifle Damage",
  "Assault Rifle Damage",
  "Rifle Damage",
  "LMG Damage",
  "SMG Damage",
  "Magazine size",
  "Reload Speed",
  "Stability",
  "Accuracy",
  "Weapon Handling",
  "Optimal Range",
  "Ammo Capacity",
  "Swap Speed",
  "Armor",
  "Health",
  "Armor Regeneration",
  "Hazard Protection",
  "Explosive Resistance",
  "Skill Tier",
  "Status Effects",
  "Skill Efficiency",
  "Skill Repair",
  "Skill Damage",
  "Skill Haste",
  "Skill Duration",
];
