import { Amplifier } from "@/lib/type";

export const ATTRIBUTES: Record<Amplifier, string[]> = {
  WD: [
    "Weapon Damage",
    "Marksman Rifle Damage",
    "Assault Rifle Damage",
    "Rifle Damage",
    "LMG Damage",
    "SMG Damage",
    "< Custom >",
  ],
  TWD: ["< Custom >"],
  AMP1: ["< Custom >"],
  AMP2: ["< Custom >"],
  AMP3: ["< Custom >"],
  CRIT_HS: [
    "Critical Hit Chance",
    "Critical Hit Damage",
    "Headshot Damage",
    "< Custom >",
  ],
  DTA_DTH: ["Damage to Armor", "Damage to Health", "< Custom >"],
  DTTOOC: ["DMG to Target out of Cover", "< Custom >"],
  ROF: ["Rate of Fire", "< Custom >"],
  None: [
    "Magazine size",
    "Reload Speed",
    "Stability",
    "Accuracy",
    "Weapon Handling",
    "Optimal Range",
    "Ammo Capacity",
    "Swap Speed",
    "Armor",
    "Health",
    "Armor Regeneration",
    "Hazard Protection",
    "Explosive Resistance",
    "Skill Tier",
    "Status Effects",
    "Skill Efficiency",
    "Skill Repair",
    "Skill Damage",
    "Skill Haste",
    "Skill Duration",
  ],
};
